# Generated by Django 4.2.4 on 2023-08-14 10:10

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='inn',
            field=models.ImageField(blank=True, null=True, upload_to=account.models.save_image),
        ),
        migrations.AddField(
            model_name='profile',
            name='ogrn',
            field=models.ImageField(blank=True, null=True, upload_to=account.models.save_image),
        ),
        migrations.AddField(
            model_name='profile',
            name='passport',
            field=models.ImageField(blank=True, null=True, upload_to=account.models.save_image),
        ),
        migrations.AddField(
            model_name='profile',
            name='snils',
            field=models.ImageField(blank=True, null=True, upload_to=account.models.save_image),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=account.models.save_image),
        ),
        migrations.AlterField(
            model_name='profile',
            name='favorites',
            field=models.ManyToManyField(blank=True, null=True, to='item.item'),
        ),
    ]
