# Generated by Django 4.2.4 on 2023-08-17 14:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_inn_profile_ogrn_profile_passport_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_online',
        ),
        migrations.AddField(
            model_name='profile',
            name='last_acivity',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 17, 19, 5, 19, 648275)),
        ),
    ]
